language: bash

env:
  - VERSION=1.7.0

matrix:
  fast_finish: true

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y gcc-multilib lynx git lib32stdc++6

before_script:
  - SMURL="http://www.gsptalk.com/mirror/sourcemod/sourcemod-$VERSION-linux.tar.gz"
  - wget $SMURL
  - SMFILE="sourcemod-$VERSION-linux.tar.gz"
  - tar -xzf $SMFILE
  - cp game_upload/addons/sourcemod/scripting/sourcebans.sp addons/sourcemod/scripting/
  - cp game_upload/addons/sourcemod/scripting/sourcecomms.sp addons/sourcemod/scripting/
  - cp game_upload/addons/sourcemod/scripting/sbchecker.sp addons/sourcemod/scripting/
  - cp game_upload/addons/sourcemod/scripting/sb_admins.sp addons/sourcemod/scripting/  
  - cp game_upload/addons/sourcemod/scripting/sb_bans.sp addons/sourcemod/scripting/
  - cp game_upload/addons/sourcemod/scripting/include/sourcebans.inc addons/sourcemod/scripting/include/
  - cp game_upload/addons/sourcemod/scripting/include/sourcecomms.inc addons/sourcemod/scripting/include/
  - cp game_upload/addons/sourcemod/scripting/include/sb_admins.inc addons/sourcemod/scripting/include/
  - cp game_upload/addons/sourcemod/scripting/include/sb_bans.inc addons/sourcemod/scripting/include/
  - cd addons/sourcemod/scripting/
  - wget https://github.com/KyleSanderson/SteamWorks/raw/master/Pawn/includes/SteamWorks.inc -O include/SteamWorks.inc
  - chmod +x spcomp
  - chmod +x compile.sh

script: 
  - ./compile.sh sourcebans.sp
  - ./compile.sh sourcecomms.sp
  - ./compile.sh sbchecker.sp
  - ./compile.sh sb_admins.sp
  - ./compile.sh sb_bans.sp

after_script:
  - ls compiled/
